### ISSUE TITLE
Does this package shows JavaScript stack trace in HockeyApp?

### ISSUE THREAD

**Issue by ranyefet** [slowpath/react-native-hockeyapp#1]
Hello,

Thanks for the package.
I'm building my iOS app with React Native and I already integrated HockeyApp SDK and simulated a crash and it appears to work.
The problem is that I can't see any relevant data to the crash (JS Error, stack trace etc) I can only see the Objective-C information.

Does this package sends JS stack trace and other data?

**Comment by iamladi** [comment]
No it does not. Would you like to try to implement this?

**Comment by ranyefet** [comment]
@martincik I'm sorry but I'm not able to implement it since we're busy releasing our app. 
We switched to Sentry which already supports tracking JS errors :)

**Comment by pickhardt** [comment]
@ranyefet I really need the JS stack traces too. I thought this project might have done it.

Did you do this:(https://docs.getsentry.com/hosted/clients/javascript/integrations/react-native/)?  It seems extremely cumbersome since you have to upload a new source map every time.  Are you doing anything better than that or just doing that each time you deploy a new app version?

**Comment by ranyefet** [comment]
@pickhardt well yeah it's a little cumbersome but It make sense, else how would they know to show a stack trace from the minified JS file? 
I wrote a little script that create a release, push it to client using CodePush and Upload bundle and source map to Sentry. Works pretty well.

**Comment by pickhardt** [comment]
Guess I'll just write a similar script too.
